[package]
name = "pubg-api"
version = "0.1.0"
authors = ["George Marshall <george@georgemarshall.name>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
json-api = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
uuid = { version = "0.6", features = ["serde"] }
